name: Deploy to NAS Server

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: homesage-spring
  SERVER_NAME: homesage-spring
  SERVER_DOCKER_IMG_NAME: homesage-spring-container
  APP_PATH: homesage-spring
  GITHUB_REPO: Son-Hunseo/HomeSage-Spring

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and Deploy Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.NAS_SERVER_IP }} -p ${{ secrets.NAS_SERVER_PORT }} << 'EOF'
          cd /volume1/${{ secrets.SSH_USERNAME }}
          rm -rf ${{ env.SERVER_NAME }}
          mkdir -p ${{ env.SERVER_NAME }}
          git clone -b main --single-branch https://github.com/${{ env.GITHUB_REPO }} ${{ env.SERVER_NAME }}
          cd ${{ env.SERVER_NAME }}

          # Build Docker image and run
          docker stop ${{ env.SERVER_DOCKER_IMG_NAME }} || true
          docker rm ${{ env.SERVER_DOCKER_IMG_NAME }} || true
          sleep 30
          docker build -t ${{ env.SERVER_DOCKER_IMG_NAME }}:latest -f Dockerfile .
          docker run -d --name ${{ env.SERVER_DOCKER_IMG_NAME }} \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            -e JWT_ACCESS_TOKEN_KEY=${{ secrets.JWT_ACCESS_TOKEN_KEY }} \
            -e JWT_REFRESH_TOKEN_KEY=${{ secrets.JWT_REFRESH_TOKEN_KEY }} \
            -e SERVER_IP=${{ secrets.SERVER_IP }} \
            -e AI_SERVER_PORT=${{ secrets.AI_SERVER_PORT }} \
            -p 8080:8080 \
            ${{ env.SERVER_DOCKER_IMG_NAME }}:latest
          EOF